#  Build stage
FROM golang:1.24.3-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o /bin/worker ./cmd/worker/main.go

# Runtime stage
FROM alpine:3.18
WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /bin/worker /app/worker
COPY --from=builder /app/internal/config /app/internal/config

ENTRYPOINT ["/app/worker"]
